# Use NVIDIA PyTorch base image
FROM nvcr.io/nvidia/pytorch:25.02-py3

# Set working directory
WORKDIR /app

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Copy the project code
COPY . .

# Default to an interactive shell so you can exec and run scripts manually.
# Override CMD in `docker run` if you want a specific script.
CMD ["/bin/bash"]

