# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/cognivault.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/cognivault.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/cognivault.proto\x12\ncognivault\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"3\n\x0cPingResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\x93\x01\n\x12ProcessDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12>\n\x08metadata\x18\x02 \x03(\x0b\x32,.cognivault.ProcessDataRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"G\n\x13ProcessDataResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\x9e\x01\n\x11\x43ogniVaultService\x12\x39\n\x04Ping\x12\x17.cognivault.PingRequest\x1a\x18.cognivault.PingResponse\x12N\n\x0bProcessData\x12\x1e.cognivault.ProcessDataRequest\x1a\x1f.cognivault.ProcessDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cognivault_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSDATAREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_PROCESSDATAREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PINGREQUEST']._serialized_start=38
  _globals['_PINGREQUEST']._serialized_end=68
  _globals['_PINGRESPONSE']._serialized_start=70
  _globals['_PINGRESPONSE']._serialized_end=121
  _globals['_PROCESSDATAREQUEST']._serialized_start=124
  _globals['_PROCESSDATAREQUEST']._serialized_end=271
  _globals['_PROCESSDATAREQUEST_METADATAENTRY']._serialized_start=224
  _globals['_PROCESSDATAREQUEST_METADATAENTRY']._serialized_end=271
  _globals['_PROCESSDATARESPONSE']._serialized_start=273
  _globals['_PROCESSDATARESPONSE']._serialized_end=344
  _globals['_COGNIVAULTSERVICE']._serialized_start=347
  _globals['_COGNIVAULTSERVICE']._serialized_end=505
# @@protoc_insertion_point(module_scope)
